const HEADER={
    NAV_ITEM_ONE:"PRODUCT",
    NAV_ITEM_TWO:"WHY WORKHALL",
    NAV_ITEM_THREE:"ABOUT US",
    NAV_ITEM_FOUR:"HELP",
    NAV_ITEM_FIVE:"CONTACT",
    NAV_ITEM_SIX:"SIGN IN",
    NAV_ITEM_SEVEN:"SIGN UP",
    
}

export default HEADER;